name: Selenium Web Scraper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scraper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.11
      - name: Initalize the project using uv
        run: uv sync --locked --all-extras --dev
      - name: Run scraper
        run: |
          uv run main.py
      - name: Make an API Request to store the scraped results
        run: |
          curl -X POST -H "Content-Type: application/zip" -d output.zip -u ${{secrets.AUTH_USER}}:${{secrets.AUTH_PASS}} https://api.uniqlotracker.com/api/products/injest
